package com.example.projectmanager.domain;

public enum AccountName {
    ANCESTORY,BNYM,CALIBO_LLC,EXPERIAN,FORD,GUARANTEED_RATE,INVOICE_CLOUD,VATTIKUTTI_VENTURES_LLC,
    ZIP_CO_US_INC, PAYPAL, JOHNSON_CONTROLS_INC, WESTERN_UNION
}
